trigger: none
pr: none

variables:
- group: Renovate Test

jobs:
- job: Renovate
  displayName: Run Renovate
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - script: >
      docker run
      --env LOG_LEVEL=debug
      --env RENOVATE_FORK_TOKEN
      --env RENOVATE_TOKEN
      --rm
      ghcr.io/renovatebot/renovate:39
    env:
      RENOVATE_REPOSITORIES: mthalman/dotnet-docker-2
      RENOVATE_FORK_TOKEN: $(RENOVATE_FORK_TOKEN)
      RENOVATE_TOKEN: $(RENOVATE_TOKEN)
